### PR TITLE
Update authorfile1.md

### PR DESCRIPTION
**Pull request by jamesyao-msft**

### CODE REVIEW

**Comment by prmerger-dev-3** [comment]
@jamesyao-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JamesYaoh** [comment]
#sign-off test

**Comment by prmerger-dev-2** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @adunndevster

**Comment by JamesYaoh** [comment]
#assign-reviewer: james-yao-msft

**Comment by prmerger-dev-4** [comment]
Invalid command: '#assign-reviewer'. Only Microsoft employees can use this command.

**Comment by jamesyao-msft** [comment]
#please-close

**Comment by meganbradley-test** [comment]
#please-open

**Comment by prmerger-dev-4** [comment]
Invalid command: '#please-open'. Only Microsoft employees can use this command.

**Comment by meganbradley-test** [comment]
#assign:meganbradley

**Comment by prmerger-dev-1** [comment]
Invalid command: '#assign'. Only Microsoft employees can use this command.

**Comment by meganbradley-test** [comment]
#unassign:adunndevster

**Comment by prmerger-dev-3** [comment]
Invalid command: '#unassign'. Only Microsoft employees can use this command.

**Comment by meganbradley-test** [comment]
#assign-reviewer:meganbradley

**Comment by prmerger-dev-4** [comment]
Invalid command: '#assign-reviewer'. Only Microsoft employees can use this command.

**Pull request closed without merging**
