### PR TITLE
test Update auto-merge.md

### PR DESCRIPTION
**Pull request by jamesyao-msft**

### CODE REVIEW

**Comment by jamesyao-msft** [comment]
#pri1

**Comment by jamesyao-msft** [comment]
#sign-off

**Comment by jamesyao-msft** [comment]
#pri1

**Comment by jamesyao-msft** [comment]
#label:pri1

**Comment by jamesyao-msft** [comment]
#label:"pri1"

**Comment by jamesyao-msft** [comment]
#sign-off

**Comment by jamesyao-msft** [comment]
#sign-off

**Comment by prmerger-dev-2** [comment]
@jamesyao-msft: I'm sorry - only the author of this article, @v-caxian, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by prmerger-dev-3** [comment]
@v-caxian : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jamesyao-msft** [comment]
#sign-off

**Comment by prmerger-dev-2** [comment]
@jamesyao-msft: I'm sorry - only the author of this article, @v-caxian, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by jamesyao-msft** [comment]
#sign-off

**Comment by prmerger-dev-3** [comment]
@jamesyao-msft: I'm sorry - only the author of this article, @v-caxian, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by jamesyao-msft** [comment]
#sign-off

**Comment by prmerger-dev-4** [comment]
@jamesyao-msft: I'm sorry - only the author of this article, @v-caxian, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by jamesyao-msft** [comment]
#please-close

**Comment by jamesyao-msft** [comment]
#please-close

**Comment by jamesyao-msft** [comment]
#please-close

**Pull request closed without merging**
