### PR TITLE
update

### PR DESCRIPTION
**Pull request by bharney**

### CODE REVIEW

**Comment by PRMerger20** [comment]
You can only sign off in the main PR conversation, not in review comments. In general, the creator of the PR should sign off, not the tech reviewer.

**Comment by PRMerger14** [comment]
You can only sign off in the main PR conversation, not in review comments. In general, the creator of the PR should sign off, not the tech reviewer.

**Comment by lamebrain** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@lamebrain: I'm sorry - only the author of this article, @bharney, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request closed without merging**
